// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1cPtncpK4_Jalg_nYWrda6TVkaEmUwfs',
    appId: '1:285228582253:web:763be017fe0213ffb44664',
    messagingSenderId: '285228582253',
    projectId: 'techstore-e5aa2',
    authDomain: 'techstore-e5aa2.firebaseapp.com',
    storageBucket: 'techstore-e5aa2.firebasestorage.app',
    measurementId: 'G-MGX6364GJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx3dYtACIuJlFYhpOvQ5V89u663K8xaEM',
    appId: '1:285228582253:android:38fdcd6eaf4a71e4b44664',
    messagingSenderId: '285228582253',
    projectId: 'techstore-e5aa2',
    storageBucket: 'techstore-e5aa2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpW3O_XePHPchig0A1AgCU8xxpT6gk_28',
    appId: '1:285228582253:ios:1053e51bdf764000b44664',
    messagingSenderId: '285228582253',
    projectId: 'techstore-e5aa2',
    storageBucket: 'techstore-e5aa2.firebasestorage.app',
    iosBundleId: 'com.example.techstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpW3O_XePHPchig0A1AgCU8xxpT6gk_28',
    appId: '1:285228582253:ios:1053e51bdf764000b44664',
    messagingSenderId: '285228582253',
    projectId: 'techstore-e5aa2',
    storageBucket: 'techstore-e5aa2.firebasestorage.app',
    iosBundleId: 'com.example.techstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1cPtncpK4_Jalg_nYWrda6TVkaEmUwfs',
    appId: '1:285228582253:web:9058473e27c36c09b44664',
    messagingSenderId: '285228582253',
    projectId: 'techstore-e5aa2',
    authDomain: 'techstore-e5aa2.firebaseapp.com',
    storageBucket: 'techstore-e5aa2.firebasestorage.app',
    measurementId: 'G-6TLTG6N7BF',
  );
}
